### PR TITLE
Pass object to directives, expose result/run, support init with existing elements/data

### LINKED ISSUE #1: Pass an object to directive handlers
Currently, you can accept 4 parameters to a directive's handler. This could get long and messy so I thought instead it would be nice to pass an object with some fixed names and allow the developer to destructure it and accept the ones they need.

Removes the need for any `_` parameter names.

### PR DESCRIPTION
**Pull request by HugoDF**
Adds sample `ll-if` directive to showcase `result` + initialising inserted DOM.

Closes #1

### CODE REVIEW

**Comment by ryangjchandler** [comment]
One of my plans was to pass an object through to the directive callback instead of ordered arguments, I wonder whether the `result` method could be passed through on that object instead of being exposed globally.. what do you think?

**Comment by HugoDF** [comment]
> One of my plans was to pass an object through to the directive callback instead of ordered arguments, I wonder whether the `result` method could be passed through on that object instead of being exposed globally.. what do you think?

Yeah that would work better.

I think the other bit I've done allowing you to pass data & elements into `init` is neat but might not work long term as well.

**Comment by ryangjchandler** [comment]
Yeah, that almost allows you to only start from a specific root node I guess, handy if you're doing something with partials (via AJAX).

**Comment by ryangjchandler** [comment]
Legendary! <3

**Pull request merged**
